#Meme responder. With the use of a command, Mayumi will provide a random meme (no pictures unless someone else knows how to do that)
elif "Meme" in mesg():
  num = random.randint(0, 20)
  if(num==0):
    print("Yeet!")
  if(num==1):
    print("Noot noot!")
  if(num==2):
    print("21!")
  if(num==3)
    print("You know I had to do it to them!")
  if(num==4)
    print("According to all known laws of aviation, there is no way a bee should be able to fly. It's wings are too small to get it's fat little body off the ground. The bee, of course, flies anyways. Because bees don't care what humans think is impossible.")
  if(num==5)
    print("You like jazz?")
  if(num==6)
    print("In case you haven't noticed, I'm weird. I'm a weirdo. I don't fit in. And I don't want to fit in. Have you ever seen me without this stupid hat on? That's weird.”)
  if(num==7)
    print("Hey how ya doin lil mama lemme whisper in ya ear, tell you something ya might like to hear.")
  if(num==8)
    print("Sanic da hedgehoog.")
  if(num==9)
    print("G O T T A  G O  F A S T")
  if(num==10)
    print("You so. Fuckin. Precious. When you. s m i l e.")
  if(num==11)
    print("Waluigi time!")
  if(num==12)
    print("Wah!")
  if(num==13)
    print("Blades are for skatin'! Ya dingus.")
  if(num==14)
    print("Chris! Is that a weed???!?!?! I'm calling the police!")
  if(num==15)
    print("I'm calling the weed!")
  if(num==16)
    print("He on x-games mode")
  if(num==17)
    print("I don't have enough money for chicken nuggets...")
  if(num==18)
    print("I'm in me mum's car! Broom broom!")
  if(num==19)
    print("ADAM!")
  if(num==20)
    print("Hi welcome to Chilis!")
  if(num==21)
    print("It is wednesday my dude!")
  if(num==22)
    print("WHAT ARE THOOOOSE?!")
  if(num==23)
    print("bro")
