
#Meme responder. With the use of a command, Mayumi will provide a random meme (no pictures unless someone else knows how to do that)
elif "Meme" in mesg():
  num = random.randint(0, 20)
  if(num==0):
    print("Yeet!")
  if(num==1):
    print("Noot noot!")
  if(num==2):
    print("21!")
  if(num==3)
    print("You know I had to do it to them!")
  if(num==4)
    print("According to all known laws of aviation, there is no way a bee should be able to fly. It's wings are too small to get it's fat little body off the ground. The bee, of course, flies anyways. Because bees don't care what humans think is impossible.")
  if(num==5)
    print("You like jazz?")
  if(num==6)
    print("In case you haven't noticed, I'm weird. I'm a weirdo. I don't fit in. And I don't want to fit in. Have you ever seen me without this stupid hat on? That's weird.”)
  if(num==7)
    print("Hey how ya doin lil mama lemme whisper in ya ear, tell you something ya might like to hear.")
  if(num==8)
    print("Sanic da hedgehoog.")
  if(num==9)
    print("G O T T A  G O  F A S T")
  if(num==10)
    print("You so. Fuckin. Precious. When you. s m i l e.")
  if(num==11)
    print("Waluigi time!")
  if(num==12)
    print("Wah!")
  if(num==13)
    print("Blades are for skatin'! Ya dingus.")
  if(num==14)
    print("Chris! Is that a weed???!?!?! I'm calling the police!")
  if(num==15)
    print("I'm calling the weed!")
  if(num==16)
    print("He on x-games mode")
  if(num==17)
    print("I don't have enough money for chicken nuggets...")
  if(num==18)
    print("I'm in me mum's car! Broom broom!")
  if(num==19)
    print("ADAM!")
  if(num==20)
    print("Hi welcome to Chilis!")
  if(num==21)
    print("It is wednesday my dude!")
  if(num==22)
    print("WHAT ARE THOOOOSE?!")
  if(num==23)
    print("bro")
  if(num==24)
    print("WHAT ARE THOOOOOSE?! These are my CROCS.")
  if(num==25)
    print("What the fuck did you just fucking say about me, you little bitch? I’ll have you know I graduated top of my class in the Navy Seals, and I’ve been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I’m the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You’re fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that’s just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little “clever” comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You’re fucking dead, kiddo.")
  if(num==26)
    print("Zoo wee mama!")
  if(num==27)
    print("Fuck this shit I'm out!")
  if(num==28)
    print("(wake me up) WAKE ME UP INSIDE (can't wake up) WAKE ME UP INSIDE (S A V E  M E)")
  if(num==29)
    print("Ever since that moment I have never known peace! Snakes have begun manifesting in my house physically!")
  if(num==30)
    print("I can't sleep because of that video.")
  if(num==31)
    print("This bitch empty! YEET!")
  if(num==32)
    print(":thinking:")
  if(num==33)
    print("Mesothelioma")
  if(num==34)
    print("THE FITNESSGRAM PACER TEST")
  if(num==35)
    print("Repeating spelling mistakes made by people in the chat.")
  if(num==36)
    print("Your mother buys you mega blocks instead of legos")
  if(num==37)
    print("the NFL theme but really loudly and bass-boosted")
  if(num==38)
    print("ur band")
  if(num==39)
    print("blokt and reported")
  if(num==40)
    print("AND THEY WERE ROOMMATES! *oh my god, they were roommates.*)
  if(num==41)
    print("Who is she?")
  if(num==42)
    print("Fergie singing the national anthem")
  if(num==43)
    print("Dishonor on YOU! Dishonor on your COW!")
  if(num==44)
    print("an owl saying 'Drugs?' over and over again")
  if(num==45)
    print("In this world it's either 'x' or be 'x'ed")
  if(num==46)
    print("Water is wet")
  if(num==47)
    print("I heard you like 'meme' so I put 'meme' in your 'meme' so you can 'meme' while you 'meme')
  if(num==48)
    print("transcendence meme")
  if(num==49)
    print("Will Smith presenting something")
  if(num==50)
    print("innnnnn WEST PHILEDELPHIA BORN AND RAISED--")
  if(num==51)
    print("one does not simply--")
  if(num==52)
    print("Shadow the Hedgehog the video game")
  if(num==53)
    print("Praise the sun!")
  if(num==54)
    print("Press F to pay respects")
  if(num==55)
    print("the downfall of capitalism")
  if(num==56)
    print("Tide pods")
  if(num==57)
    print("Destroying white supremacy")
  if(num==58)
    print("Then *perish!*")
  if(num==59)
    print("Separating Florida from the rest of te united states")
  if(num==60)
    print("Nerf this!")
  if(num==61)
    print("Error 404: Meme not found")
  if(num==61)
    print("WIP")
          
          
          
          
          
          
          
