//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discord_Bot_2.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Discord_Bot_2.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye
        ///Auf Wiedersehen
        ///Peace
        ///peace out
        ///see ya
        ///cya
        ///Catch ya later
        ///Aight man I&apos;m out
        ///So long, farewell
        ///I&apos;ll be back.
        ///Smell you later!
        ///Hasta la vista, baby.
        ///Sayonara
        ///Adieu, adieu, parting is such sweet sorrow..
        /// </summary>
        public static string goodbye {
            get {
                return ResourceManager.GetString("goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodnight
        ///G&apos;night
        ///night.
        /// </summary>
        public static string goodnight {
            get {
                return ResourceManager.GetString("goodnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello
        ///Hullo
        ///Greetings
        ///Hallo
        ///Wazzup
        ///What&apos;s up
        ///Yo
        ///Aiyo
        ///How ya doing?
        ///What&apos;s good?
        ///sup
        ///Hey
        ///&apos;ello
        ///Oh. Its you.
        ///Hei. Kuinka voit?
        ///Hola
        ///Its n_ice_ to meet you!
        ///Hello. Its me.
        ///&apos;ello guv&apos;nor
        ///Greetings Human.
        ///Salutations!.
        /// </summary>
        public static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kek
        ///lol
        ///LOL
        ///haha.
        /// </summary>
        public static string laugh {
            get {
                return ResourceManager.GetString("laugh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rip in pepperonis
        ///RIP in pieces.
        /// </summary>
        public static string rip {
            get {
                return ResourceManager.GetString("rip", resourceCulture);
            }
        }
    }
}
